### ISSUE TITLE
change_ordering in constant layer

### ISSUE THREAD

**Issue by weiyichang** [nerox8664/onnx2keras#21]
Hi,
My version of onnx2keras is 0.0.9

When I transform my model, I encounter following error:

File "/usr/local/lib/python3.6/dist-packages/onnx2keras/constant_layers.py", line 11, in convert_constant
    if node_name['change_ordering']:
TypeError: string indices must be integers

I'm not ensure if I ignore 'change_ordering' here is ok, just want to check it

Moreover, I can transform my model successfully with 0.0.3 

Thanks!

**Comment by nerox8664** [comment]
Hello @weiyichang!
Please upgrade your version to `0.0.10`, hope it'll fix the problem.

**Comment by weiyichang** [comment]
Hi,
Thanks for your quick response

I check constant layer in the version 0.0.10, so ignoring the change_ordering param is ok, right?

Now version 0.0.10 can work with my model
