### ISSUE TITLE
TypeError: unhashable type: 'google.protobuf.pyext._message.RepeatedScalarContaine'

### ISSUE THREAD

**Issue by emanuelcovaci** [nerox8664/onnx2keras#23]
I try to convert an ONNX model to Keras, but when I call the conversion function I receive the following error message ``` "TypeError: unhashable type: 'google.protobuf.pyext._message.RepeatedScalarContainer'"```

You can see the ONNX Model here: https://ibb.co/sKnbxWY

```python
import onnx2keras
from onnx2keras import onnx_to_keras
import keras
import onnx

onnx_model = onnx.load('onnxModel.onnx')
k_model = onnx_to_keras(onnx_model, ['input_1'])

keras.models.save_model(k_model,'kerasModel.h5',overwrite=True,include_optimizer=True)
```

```shell
File "C:/../onnx2Keras.py", line 7, in <module>
    k_model = onnx_to_keras(onnx_model, ['input_1'])
  File "..\site-packages\onnx2keras\converter.py", line 80, in onnx_to_keras
    weights[onnx_extracted_weights_name] = numpy_helper.to_array(onnx_w)
TypeError: unhashable type: 'google.protobuf.pyext._message.RepeatedScalarContainer'
```

**Comment by nerox8664** [comment]
Hello @emanuelcovaci.
Can you share your ONNX model so I can reproduce the error?
In your error message I see the issue related to onnx weights loading, not to the model architecture, because actual conversion hasn't even started.

**Comment by emanuelcovaci** [comment]
Hello @nerox8664 

Here you can find the model https://drive.google.com/open?id=1oQTzQ0BO6msO_djhbgsdvpaM22PLtn49

**Comment by nerox8664** [comment]
Please, try to convert your model with updated version of the library.
` pip install --upgrade onnx2keras`

Also, use `name_policy='renumerate'` parameter to fix naming error.

**Comment by emanuelcovaci** [comment]
It's working fine now. Thank you

**Comment by xXDarkCubeXx** [comment]
I still have this error

**Comment by mdhimes** [comment]
I'm on the latest version via pip (0.0.22), and I am getting this same error.
