### ISSUE TITLE
AttributeError: 'ParsedRequirement' object has no attribute 'req'

### ISSUE THREAD

**Issue by pranv12** [nerox8664/onnx2keras#63]
I'm trying to install `onnx2keras` module but while installing I got error. I tried installing using both `pip` and source directory. Error is always same. Is there any dependency I've to install?

`Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    reqs = [str(ir.req) for ir in install_reqs]
  File "setup.py", line 16, in <listcomp>
    reqs = [str(ir.req) for ir in install_reqs]`
`AttributeError: 'ParsedRequirement' object has no attribute 'req'
`

**Comment by nerox8664** [comment]
Hello @pranv12.
The problem is probably caused by new `pip` version. I will update `setup.py` soon.

**Comment by YuanTingHsieh** [comment]
A quick fix before the update of setup.py
You can do pip install pip==20.0.2 and then pip install onnx2keras will work

**Comment by pranv12** [comment]
Downgrading pip to 20.0.2 worked. Thanks.
