### ISSUE TITLE
version 0.0.21 raise error "adjusted"

### ISSUE THREAD

**Issue by M-Tonin** [nerox8664/onnx2keras#72]
I have upgrade  onnx2keras and it gave the error:
(I will catch again,  for now using onnx2keras v0.0.20)

When I downgrade the error is not raise.

**Comment by nerox8664** [comment]
Hello @M-Tonin .
Can you provide more information? Code snippet or/and a full program log.

**Comment by M-Tonin** [comment]
![image](https://user-images.githubusercontent.com/21134353/83405252-7d661580-a3e2-11ea-92e5-91f796756b9c.png)

**Comment by M-Tonin** [comment]
![image](https://user-images.githubusercontent.com/21134353/83405723-873c4880-a3e3-11ea-9f9a-de8e781518fa.png)

**Comment by nerox8664** [comment]
got it, thanks. It's an error in debug output, I will disable it in future version.
